# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deaca88cfa6350df050018a95d11e9c022445b6f63784ea01797968fdfbc8d01ed286fcfa89a785b70994240ee94189a6ebb7e1381e542795e9777d808d4e658

test:
  secret_key_base: 159d87954e3a80f21eb7bb4f8d60a05015c84b4f3cb8122252687fc8d4472143b409c5c33133f4a08002341f7cc6eb35dc527623660c7531b61f00d2e7547226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
